FUNCTION ZFM_VENDOR_INVDOWNLOAD_YM.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IV_DOC) TYPE  RE_BELNR
*"     VALUE(IV_USERNAME) TYPE  LIFNR
*"  EXPORTING
*"     VALUE(P_PDF) TYPE  XSTRING
*"----------------------------------------------------------------------
DATA: lv_func    TYPE funcname VALUE 'ZF_VENDORFORM_YM',   "Adobe form FM name
        lv_out     TYPE sfpoutputparams,
        lv_doc     TYPE sfpdocparams,
        lv_form    TYPE fpformoutput,
        lv_xstring TYPE xstring.

  DATA: lt_invoice TYPE ZTT_VEN_INVDOWNLOAD_YM .

  " Step 1: Select invoice data
  SELECT a~belnr,
         a~gjahr,
         a~blart,
         a~bldat,
         a~usnam,
         a~bukrs,
         a~waers,
         a~rmwwr,
         a~wmwst1,
         b~ebeln,
         b~ebelp,
         b~matnr,
         b~werks,
         b~wrbtr,
         b~menge,
         b~bstme
    INTO CORRESPONDING FIELDS OF TABLE @lt_invoice
    FROM rbkp AS a
    INNER JOIN rseg AS b ON a~belnr = b~belnr AND a~gjahr = b~gjahr
    WHERE a~belnr = @iv_doc.

  IF sy-subrc <> 0.
    MESSAGE 'No data found for given document' TYPE 'E'.
  ENDIF.

  " Step 2: Set Adobe output parameters
  lv_out-getpdf   = abap_true.
  lv_out-nodialog = abap_true.

  " Step 3: Open Adobe job
  CALL FUNCTION 'FP_JOB_OPEN'
    CHANGING
      ie_outputparams = lv_out
    EXCEPTIONS
      cancel          = 1
      usage_error     = 2
      system_error    = 3
      internal_error  = 4
      OTHERS          = 5.
  IF sy-subrc <> 0.
    MESSAGE 'FP_JOB_OPEN failed' TYPE 'E'.
  ENDIF.

  " Step 4: Get generated Adobe form FM name
  CALL FUNCTION 'FP_FUNCTION_MODULE_NAME'
    EXPORTING
      i_name     = lv_func
    IMPORTING
      e_funcname = lv_func
    EXCEPTIONS
      OTHERS = 1.
  IF sy-subrc <> 0.
    MESSAGE 'FP_FUNCTION_MODULE_NAME failed' TYPE 'E'.
  ENDIF.

  " Step 5: Call Adobe form FM
  CALL FUNCTION lv_func
    EXPORTING
      /1BCDWB/DOCPARAMS = lv_doc
      iv_doc            = iv_doc
      iv_username       = iv_username
      it_invoice        = lt_invoice
    IMPORTING
      /1BCDWB/FORMOUTPUT = lv_form
    EXCEPTIONS
      usage_error     = 1
      system_error    = 2
      internal_error  = 3
      OTHERS          = 4.
  IF sy-subrc <> 0.
    MESSAGE 'Adobe form execution failed' TYPE 'E'.
  ENDIF.

  " Step 6: Close Adobe job
  CALL FUNCTION 'FP_JOB_CLOSE'
    EXCEPTIONS
      usage_error    = 1
      system_error   = 2
      internal_error = 3
      OTHERS         = 4.

  " Step 7: Validate and return PDF
  IF lv_form IS INITIAL OR lv_form-pdf IS INITIAL.
    MESSAGE 'No PDF generated by Adobe form' TYPE 'E'.
  ENDIF.

  lv_xstring = lv_form-pdf.
  p_pdf = lv_xstring.




ENDFUNCTION.
